name: Coverage with CodeClimate
on: [push, pull_request]
jobs:
  codeclimate-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16'
    - run: go build
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: d7843db3713aa45c874e25cd6ba938666cc580201598706fa6be5960d9f0a61d
      with:
        coverageCommand: go test ./... -coverprofile c.out
        prefix: github.com/ryanande/cobraui
